server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: xiang-picture-backend
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/xiang_picture
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 开放更大的文件上传限制
  servlet:
    multipart:
      max-file-size: 10MB
  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  # session配置
  session:
    store-type: redis
    # session 30天过期
    timeout: 2592000
  # 空间图片分表
  shardingsphere:
    datasource:
      names: xiang_picture
      xiang_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xiang_picture
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: xiang_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.xiangzi.xiangpicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true

#  profiles:
#    active: local

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #逻辑删除字段名
      logic-delete-value: 1 #逻辑删除值
      logic-not-delete-value: 0 #逻辑未删除值
    enable-sql-runner: true

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xiangzi.xiangpicturebackend.controller

# 阿里云 AI 配置
aliYunAi:
  apiKey: sk-96e257cd02c1427481c0ac4879160f7b